apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy210677
  labels:
    app: autodeploy210677
  namespace: namespace-workflow-1695389786514
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy210677
  template:
    metadata:
      labels:
        app: autodeploy210677
    spec:
      containers:
        - name: autodeploy210677
          image: acrworkflow1695389786514.azurecr.io/image-workflow-1695389786514:latest
          ports:
            - containerPort: 5000